name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  THEMOVIEDB_API_KEY: ${{ secrets.THEMOVIEDB_API_KEY }}
  NEXT_PUBLIC_EMULATE_FIREBASE: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Start Firebase emulator in the background
        run: pnpm run emulate &

      - name: Pretty?
        run: pnpm run prettier:check

      - name: TypeScript?
        run: pnpm run tsc

      - name: Run lint
        run: pnpm run lint

      - name: Cache Next build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-nextjs-

      - name: Run build script
        run: pnpm run build

      - name: Start
        env:
          PORT: 3000
        run: |
          pnpm run start > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Check that the server started
        run: curl --retry-connrefused --retry 3 -I http://localhost:3000/

      - name: Wait for emulators
        run: |
          set -e

          echo "Show emulator home"
          curl --retry-connrefused --retry 6 http://localhost:4000
          echo "View Auth emulator home"
          curl --fail http://localhost:4000/auth
          echo "View Firestore emulator home"
          curl --fail http://localhost:4000/firestore

      - name: View the home page
        run: |
          curl -v --fail http://localhost:3000/

      # If you're NOT going to use `--project="Google Chrome"` when running
      # the Playwright tests, uncomment these lines. They're very slow
      # - name: Install Playwright Browsers
      #   run: pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm dlx playwright test --project="Google Chrome"

      - name: Debug any server outputs
        if: failure()
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
